### ISSUE TITLE
how to transfer from new version to old version

### ISSUE THREAD

**Issue by ivanwu0404** [tatp22/multidim-positional-encoding#38]
Hi, 

I trained a model with the new version, the usage for ```PositionalEncoding1D``` is 
```python
from positional_encodings.torch_encodings import PositionalEncoding1D
``` 
But for some reasons, I need to load the trained model with old version (5.0.0), the usage changed to
```python
from positional_encodings import PositionalEncoding1D
``` 
So when I load my model file 
```python 
torch.load('model.pth')
```
it will occur an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'positional_encodings.torch_encodings'
```
Can there be any method to fix except for update the version?

**Comment by tatp22** [comment]
Hey, I don't quite understand. So you trained your model with version `>6.0.1`:

```python
from positional_encodings.torch_encodings import PositionalEncoding1D
model.train()
```

And then in your current binary (`5.0.0`), you have to do the following:

```python
from positional_encodings import PositionalEncoding1D
torch.load('model.pth')
```

And this is where you get your error?

If this is the case unfortunately I don't have too much knowledge about this situation. There might be something in the [args](https://github.com/pytorch/pytorch/blob/b2a318d8567cbf6ebb67af01782963324d7e99a4/torch/serialization.py#L912) when you call `load()` that might solve this issue. Why not start there? [This](https://docs.python.org/3/library/pickle.html#pickle.Unpickler) might also help.

**Comment by tatp22** [comment]
Closing due to inactivity.
